"""adds payer_name to payments

Revision ID: 461595a10b96
Revises: 7e79fdbb8c96
Create Date: 2026-09-15 15:00:03.156837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461595a10b96'
down_revision: Union[str, Sequence[str], None] = '7e79fdbb8c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payer_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payer_name')
    # ### end Alembic commands ###
